name: CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  push_to_registry:
    name: Deploy docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Build and push docker image
        id: build_request
        uses: tyrrrz/action-http-request@v1
        with:
          # Required
          url: http://api.null.care/build
          # Optional (default: GET)
          method: POST
          # Optional (default: no headers)
          headers: |
            Content-Type: application/json
            x-api-key: ${{ secrets.API_KEY }}
          # Optional (default: no body)
          body: |
            {
              "repository": "${{ github.repository }}",
              "context": ".",
              "tag": "docker-dashboard:latest"
            }

      - name: Build output
        run: |
          echo "Status: ${{ steps.build_request.outputs.status }}"
          echo "Body: ${{ steps.build_request.outputs.body }}"
          
      - name: Deploy image on server
        id: run_request
        uses: tyrrrz/action-http-request@v1
        with:
          url: http://api.null.care/run
          method: POST
          headers: |
            Content-Type: application/json
            x-api-key: ${{ secrets.API_KEY }}
          body: |
            {
              "image": "registry.null.care/docker-dashboard:latest",
              "name": "docker-dashboard",
              "port": "9550:5000",
              "args": ["-e", "ApiKey=${{ secrets.CONTAINER_API_KEY }}", "-v", "/var/run/docker.sock:/var/run/docker.sock"]
            }

      - name: Deploy output
        run: |
          echo "Status: ${{ steps.request.run_request.status }}"
          echo "Body: ${{ steps.request.run_request.body }}"
